name: Additional Workflow
on:
  push:
  schedule:
    - cron: "0 * * * *"
jobs:
  Build-the-Thing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."

  Test-the-Thing:
    needs: Build-the-Thing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Hit itttttttt
        run: cd ${{ github.workspace }}
      - run: chmod +x main.py
      - run: ./main.py
      - name: Get code coverage
      - run: python test-coverage.py > coverage.txt
      - name: Send event to Compass
        run: echo "emitting a build/test event to the Compass activity feed!"

  Deploy-the-Thing:
    needs: Test-the-Thing
    runs-on: ubuntu-latest
    steps:
      - name: Fake deploy to AWS
        run: echo "yep, totallllly deploying to AWS right meow..."
      - name: Send deployment event to Compass
        run: echo "emitting a deployment event to the Compass activity feed!"
